name: Test [Backend]

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./qalam
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Build
        run: |
            cargo build --release --verbose
            # Tell the size of binary
            pwd && ls -la . # du -s 

      - name: Run lint
        run: cargo clippy --verbose

#      - name: Run tests
#        run: cargo test --verbose